#pragma once

#include "GeneratorBase.hpp"

namespace Wordclock
{
	/// converts all RGB color generated by the Generator into HSV colors.
	/// Note that they still use CRGB objects to be represented for
	/// compatibility reasons with other color generators.
	/// @tparam Generator - the underlying generator whose colors are converted
	///                     into HSV colors.
	template <class Generator>
	class GeneratorHSVAdapter : public GeneratorBase
	{
	protected:
		typedef GeneratorBase super;
		Generator gen;
	public:
		GeneratorHSVAdapter();
		CRGB next();
	};

	template <class Generator>
	GeneratorHSVAdapter<Generator>::GeneratorHSVAdapter()
	{
		gen = Generator();
	}

	template <class Generator>
	CRGB GeneratorHSVAdapter<Generator>::next()
	{
		CHSV color = rgb2hsv_approximate(gen.next());
		return CRGB(color.h, color.s, color.v);
	}
}